version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desarrollo
    volumes:
      - dbDesarrollo:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbDesarrollo:
